name: Publish Docker GHCR Image

on:
  release:
    types: [published]
  push:
    branches:
      - "fix/ci-ghcr"
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag for the Docker image"
        required: true
        default: "1.2.5"
        type: string
permissions:
  contents: read
  packages: write

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            RELEASE_TAG="${{ github.event.release.tag_name }}"
            tag="${RELEASE_TAG#v}"
            echo "tag=$tag" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image (${{ matrix.platform }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/snouzy/workout-cool:test
            ghcr.io/snouzy/workout-cool:latest
          platforms: ${{ matrix.platform }} # Use the platform from the matrix
