name: Publish Docker GHCR Image

on:
  release:
    types: [published]
  push:
    branches:
      - "fix/ci-ghcr"
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag for the Docker image"
        required: true
        default: "1.2.5"
        type: string
permissions:
  contents: read
  packages: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    outputs:
      image-digest-${{ matrix.platform }}: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        id: vars
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            RELEASE_TAG="${{ github.event.release.tag_name }}"
            tag="${RELEASE_TAG#v}"
            echo "tag=$tag" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest" >> $GITHUB_OUTPUT
          fi

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image (${{ matrix.platform }})
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: ${{ matrix.platform }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/workout-cool:${{ steps.vars.outputs.tag }}-${{ matrix.platform }}
            ghcr.io/${{ github.repository_owner }}/workout-cool:latest
          outputs:
            type=image,name=ghcr.io/${{ github.repository_owner }}/workout-cool,annotation-index.org.opencontainers.image.ref.name=${{
            steps.vars.outputs.tag }}-${{ matrix.platform }}

  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t ghcr.io/${{ github.repository_owner }}/workout-cool:latest \
            -t ghcr.io/${{ github.repository_owner }}/workout-cool:${{ github.ref_name }} \
            ghcr.io/${{ github.repository_owner }}/workout-cool:${{ needs.build.outputs['image-digest-linux/amd64'] }}-linux/amd64 \
            ghcr.io/${{ github.repository_owner }}/workout-cool:${{ needs.build.outputs['image-digest-linux/arm64'] }}-linux/arm64
