name: Publish Docker GHCR Image

on:
  release:
    types: [published]
  push:
    branches:
      - "fix/ci-ghcr"
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag for the Docker image"
        required: true
        default: "1.2.5"
        type: string
permissions:
  contents: read
  packages: write

jobs:
  # This job just generates the tags and labels to be shared by the matrix jobs
  meta:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{version}},value=latest
            type=raw,value=${{ github.event.inputs.version }},enable=${{ github.event_name == 'workflow_dispatch' }}

  # build job runs in parallel for each platform
  build:
    needs: meta
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # builds and pushes a platform-specific image
      - name: Build and push platform-specific image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # Note the platform-specific tag suffix
          tags: ${{ needs.meta.outputs.tags }}-${{ matrix.platform }}
          labels: ${{ needs.meta.outputs.labels }}
          platforms: ${{ matrix.platform }}

  # final job runs after all builds are complete to create the final manifest
  publish-manifest:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push the multi-platform manifest
        run: |
          docker buildx imagetools create \
            ${{ needs.meta.outputs.tags }}-${{ matrix.platform }} \
            --tag ${{ needs.meta.outputs.tags }}
